language: python
services: docker
git:
  depth: 1
jobs:
  include:
    - stage: check
      name: Tests
      script: echo "stage CHECK"
    - stage: deploy
      name: Kubernetes
      script: "stage DEPLOY"
      if: (branch = master AND type = push) OR tag IS present
#stages:
#  - name: check
#  - name: deploy
#    if: (branch = master AND type = push) OR tag IS present
notifications:
  email: false
